import type { Metadata } from 'next';

// use can use this in page too and this can be dynamic meta data and layout one is dynamic
export const metadata: Metadata = {
  title: 'About',
  description: 'Generated by create next app',
};

const About = async () => {
  // throw new Error('hello');
};
export default About;
